import Head from 'next/head'

export default function Home(): React.ReactElement {
    return (
        <div className="max-w-lg w-full mx-auto py-8">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1 className="text-xl text-red-600 text-center">Welcome To My Portfolio!</h1>
            </main>
        </div>
    )
}
